name: Label PR
on:
  pull_request:
    branches:
    - main

jobs:
  semver:
    name: Minimal Semver Labels
    runs-on: ubuntu-latest
    steps:
    - name: Auto-label Semver
      uses: paketo-buildpacks/github-config/actions/pull-request/auto-semver-label@autolabel
    - uses: mheap/github-action-required-labels@v1
      with:
        count: 1
        labels: semver:major, semver:minor, semver:patch
        mode: exactly
